remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Applied Deep Learning
description: ECBS5200 — Practical Deep Learning Engineering for Applied ML · CEU Vienna · Spring 2026
